learning_log/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls', namespace='learning_logs')),
    path('users/', include('users.urls', namespace='users')),

]

learning_logs/urls.py
"""DEFINE URL PATTERNS FOR LEARNING LOGS"""
from django.urls import path
from . import views 


app_name = 'learning_logs'

urlpatterns = [
    # Homepage
    path('', views.index, name='index'),

    #SHOW ALL TOPICS PAGE PATH
    path('topics/', views.topics, name='topics'),

    #DETAIL PAGE FOR A SINGLE TOPIC 

    path('topics/<int:topic_id>/', views.topic, name='topic'),


    #PAGE FOR ADDING A  NEW TOPIC 
     path('new_topic/', views.new_topic, name='new_topic'),


     #PAGE FOR ADDING NEW ENTRY 

    
     path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),

     #PAGE TO EDIT ENTRY 

    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),





]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView

from . import views

app_name = 'users'

urlpatterns = [
    # LOGIN PAGE 
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    
    #LOGOUT PATH
    path('logout/', views.logout_view, name='logout'),

   #REGISTRATION URL 
    path('register/', views.register, name='register'),
]


learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User 

#we will need to create models such as class to tell Django how to work 
#with the data we will be providing .
#Our users need to create a topic they are learning and we will need to keep 
#time stamp of each learning logs .

class Topic(models.Model):
	"""A topic the user is learning about """
	text= models.CharField(max_length=200)
	date_added= models.DateTimeField(auto_now_add=True)
	owner=models.ForeignKey(User,on_delete=models.CASCADE)

	def __str__(self):
		"""Return a string version of the model or our class"""
		return self.text


class Entry(models.Model):
	"""what the user learned about a topic"""
	topic= models.ForeignKey(Topic,on_delete=models.CASCADE)
	text= models.TextField()
	date_added= models.DateTimeField(auto_now_add=True)


	class Meta:
		verbose_name_plural="entries"

	def __str__(self):
		"""return a string """

		if len(self.text) > 50:
			return self.text[:50] + "...."
		else:
			return  self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms 

from . models import Topic,Entry


class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic 
		fields= ['text']
		labels= {'text':''}

class EntryForm(forms.ModelForm):
	class Meta:
		model= Entry
		fields=['text']
		labels={'text':''}
		widgets={'text': forms.Textarea(attrs={'cols':80})}


learning_logs/views.py

from django.shortcuts import render
from django.http import HttpResponseRedirect,Http404
from django.urls import reverse
from .models import Topic
from .models import Entry
from .forms import EntryForm
from django.contrib.auth.decorators import login_required
from .forms import TopicForm






#creating the homepage view 
def index(request):
	"""The homepage for learning logs"""
	return render(request,'learning_logs/index.html')

def check_topic_owner(request,topic):
	if topic.owner != request.user:
		 raise Http404

#CREATING THE TOPICS VIEW 
@login_required
def topics(request):
	"""SHOW ALL TOPICS"""
	topics= Topic.objects.filter(owner=request.user).order_by('date_added')
	context= {'topics':topics}
	return render(request, "learning_logs/topics.html",context)


#GET A TOPIC AND ALL THE ENTRIES ON THAT TOPIC
@login_required
def topic(request,topic_id):
	"""SHOW A SINGLE TOPIC AND ALL THE ENTRIES"""
	topic= Topic.objects.get(id=topic_id)
	#make sure the topic belongs to the user 
	# if topic.owner != request.user:
	# 	raise Http404
	check_topic_owner(request,topic)

	entries=topic.entry_set.order_by('-date_added')
	context= {'topic':topic,'entries':entries}
	return render(request,"learning_logs/topic.html",context)


@login_required
def new_topic(request):
	"""ADD NEW TOPIC VIEW """
	if request.method != 'POST':
		#NO DATA HAS BEEN SUBMITTED SO CREATE A BLANK FORM
		form= TopicForm()
	else:
		#DATA HAS BEEN SUBMITTED PROCESS THE DATA
		form= TopicForm(data=request.POST)
		if form.is_valid():
			new_topic=form.save(commit=False)
			new_topic.owner=request.user 
			new_topic.save()

			return HttpResponseRedirect(reverse('learning_logs:topics'))
	context= {'form':form}
	return render(request,'learning_logs/new_topic.html',context)




#uses the topic id to assign to a specific topic
@login_required
def new_entry(request,topic_id):
	"""ADD A NEW ENTRY FOR A PARTICULAR TOPIC"""
	topic=Topic.objects.get(id=topic_id)

	if topic.owner != request.user:
		raise Http404

	if request.method != 'POST':
		#NO DATA HAS BEEN SUBMITTED SO CREATE A BLANK FORM
		form= EntryForm()
	else:
		#DATA HAS BEEN SUBMITTED PROCESS THE DATA
		form= EntryForm(data=request.POST)
		if form.is_valid():
			#we should save it and make sure its get to the database 
			new_entry=form.save(commit=False)
			new_entry.topic=topic
			new_entry.save()
			return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic_id]))
	context= context= {'topic':topic,'form':form, 'topic_id': topic.id}
	return render(request,'learning_logs/new_entry.html',context)





# EDITING OUT ENTRY 
@login_required
def edit_entry(request,entry_id):
	"""Edit an existing entry """
	entry=Entry.objects.get(id=entry_id)
	topic=entry.topic 

	# check_topic_owner(request,topic)

	if topic.owner != request.user:
		raise Http404

	if request.method != 'POST':
		#Initial request, prefill form with the current entry
		form= EntryForm(instance=entry)
	else:
		#POST DATA SUBMITTED, PROCESS DATA
		form=EntryForm(instance=entry,data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic.id]))
	context= {'entry':entry,'topic':topic,'form':form}
	return render(request,'learning_logs/edit_entry.html',context)



users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm


# Create your views here.

def logout_view(request):
	"""LOG THE USER OUT"""
	logout(request)
	return HttpResponseRedirect(reverse('learning_logs:index'))


def register(request):
	"""REGISTER NEW USER"""
	if request.method != 'POST':
		#Display blank registration form
		form=UserCreationForm()

	else:
		#GET REGISTERATION DETAILS AND PROCESS
		form=UserCreationForm(data=request.POST)
		if form.is_valid():
			new_user= form.save()
			#LOG THE USER IN AND THEN REDIRECT TO HOMEPAGE 
			authenticate_user=authenticate(username=new_user.username,password=request.POST['password1'])
			login(request, authenticate_user)
			return HttpResponseRedirect(reverse('learning_logs:index'))

	context= {'form':form}
	return render(request,'users/register.html',context)





learning_logs/templates/learning_logs/base.html
{% load static %}
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StudyStacks</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static  'learning_logs/style.css' %}">

    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body class="study-body">
    
    <!--STATIC NAV BAR -->
    <nav class="navbar navbar-default study-navbar">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'learning_logs:index' %}">StudyStacks</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a href="#">Hello, {{user.username}}.</a></li>
                        <li><a href="{% url 'users:logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'users:register' %}">Register</a></li>
                        <li><a href="{% url 'users:login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
    </nav>

     <div class="container study-container">
        <div class="page-header study-header">
            {% block header %}{% endblock header %}
        </div>

        <div class="study-content">
            {% block content %}{% endblock content %}
        </div>  
     </div> 


    
     
     

    <footer class="study-footer">
        <div class="container text-center">
            <a href=""><i class="fab fa-instagram fa-2x"></i></a>
            <a href="#"><i class="fab fa-twitter fa-2x"></i></a>
            <p>Email: info@example.com</p>
            <p>Address: 123 Street, City, Country</p>
        </div>
    </footer>
    
</body>
</html>










learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}} </a> </p>

<p>Edit entry:</p>

<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>

	{% csrf_token %}
	{% bootstrap_form form %}
	{% buttons %}
	<!-- {{form.as_p}} -->

	<button name="submit" class="btn btn-primary">save changes</button>

	{% endbuttons %}
	
</form>


{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}


{% block header %}

<div class="jumbotron study-jumbotron">
	<h1>The Smarter Way to Study</h1>
</div>
{% endblock header %}

{% block content %}
<h2>
	<a href="{% url 'users:register' %}">Register an account </a>
	and Step into a World of Streamlined Learning:Join Study Stacks Now!
</h2>

<h2>
	Maximize your learning with Study Stacks! Easily create topics and entries as you master new concepts. Reinforce knowledge, revisit insights, and curate your unique learning journey. Start building your Study Stacks today!
</h2>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h3>Add a new entry</h3>
{% endblock header %}

{% block content %}

<p> <a href="{% url 'learning_logs:topic' topic.id %}"> {{topic}}</a>  </p>

<!-- <p>Add a new entry:</p> -->

<form action="{% url 'learning_logs:new_entry' topic_id %}" method='post'>

	{% csrf_token %}
	{% bootstrap_form form %}
	{% buttons %}
	<!-- {{form.as_p}} -->
	<button name="submit" class="btn btn-primary">add entry</button>
	{% endbuttons %}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}


{% block header %}
<h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}

<form action="{% url 'learning_logs:new_topic' %}" method="post" class="form">
	{% csrf_token %}
	{% bootstrap_form form %}
	{% buttons %}
	<button name="submit" class="btn btn-primary">add topic</button>
	{% endbuttons %}
</form>
{% endblock content %}


learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}


{% block header %}
<h2>{{topic}}</h2>
{% endblock header %}



{% block content %}
<p><a href="{% url 'learning_logs:new_entry' topic.id %}"> Add new entry </a> </p>


	{% for entry in entries %}
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3>
				{{entry.date_added|date:'M d, Y H:i'}}
				<small>
					<a href="{% url 'learning_logs:edit_entry' entry.id %}"> edit entry </a>
				</small>
			</h3>
		</div>
		
	</div>
	<div class="panel-body">
		{{ entry.text|linebreaks }}
	</div>

	
	{% empty %}

	There are no entries for this topic yet.

	{% endfor %}


{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}



{% block header %}
<h1>Topics:</h1>
{% endblock header %}


{% block content %}



<ul>

	{%  for topic in topics   %}
	<h3>
	 <li>
	 <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
	</li>
    </h3>

	{% empty %}
	 <li>No topics have been added yet.</li>
	{% endfor %}
</ul>

<h3><a href="{% url 'learning_logs:new_topic'  %}">Add a new topic</a></h3>

{% endblock content %}


users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{%  block header %}
<h2>Log in to your account</h2>
{% endblock header %}


{% block content %}

<form method="post" action="{% url 'users:login' %}" class="form">
	{% csrf_token %}
	
	{% bootstrap_form form %}
	{% buttons %}
	<button name="submit" class="btn btn-primary">log in </button>
    {% endbuttons %}
	<input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>
</form>
{% endblock content %}


users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{%  block header %}
<h2>Create account</h2>
{% endblock header %}

{% block content %}

<form method="post" action="{% url 'users:register' %}" class="form">
	{% csrf_token %}
	{% bootstrap_form form %}
	{% buttons %}
	<button name="submit" class="btn btn-primary">register </button>
     {% endbuttons %}
	<input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>
</form>
{% endblock content %}
